### ISSUE TITLE
There is no license

### ISSUE THREAD

**Issue by amitbet** [elgs/filesync#2]
HI,

Can I ask about the license of this code?
Most GO code is MIT, but repo this has no license...
I actually just thought of creating something for home usage, but it would help to know.

Thanks,
           Amit.

**Comment by elgs** [comment]
I don't have a copy of MIT license text in my hand. Is ISC ok? It looks also pretty permissive.

**Comment by amitbet** [comment]
Mit:
https://tldrlegal.com/license/mit-license#fulltext

Isc:
https://tldrlegal.com/license/-isc-license#fulltext

They both are very close, you can choose..

**Comment by elgs** [comment]
Sorry for coming back late. It should be sorted out.

**Comment by amitbet** [comment]
Thanks 👍
